[versions]
agp = "8.7.0"
androidx-core = "1.13.1"
appcompat = "1.7.0"
constraintlayout = "2.1.4"
coroutines = "1.9.0"
expresso-core = "3.6.1"
ext-junit = "1.2.1"
hilt = "2.52"
junit = "4.13.2"
kotlin = "2.0.20"
kotlin-serialization = "1.7.3"
ksp = "2.0.20-1.0.25"
lifecycle = "2.8.6"
logging-interceptor = "5.0.0-alpha.14"
material = "1.12.0"
navigation = "2.8.1"
preference = "1.2.1"
recyclerview = "1.3.2"
recyclerview-selection = "1.1.0"
retrofit = "2.11.0"
room = "2.6.1"
swiperefreshlayout = "1.1.0"

[libraries]
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
expresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "expresso-core" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "ext-junit" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlin-serialization-converter = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-compiler = { group = "androidx.lifecycle", name = "lifecycle-compiler", version.ref = "lifecycle" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
recyclerview-selection = { group = "androidx.recyclerview", name = "recyclerview-selection", version.ref = "recyclerview-selection" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name="swiperefreshlayout", version.ref ="swiperefreshlayout" }

[bundles]
retrofit = ["kotlin-serialization-converter", "logging-interceptor", "retrofit"]
room = ["room-runtime", "room-ktx"]

[plugins]
agp = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
