[versions]
accompanist = "0.34.0"
agp = "8.5.2"
appcompat = "1.7.0"
activity = "1.9.1"
compose-foundation = "1.7.0-rc01"
compose-material = "1.7.0-rc01"
compose-material3 = "1.3.0-rc01"
compose-material3-adaptive = "1.0.0-rc01"
compose-navigation = "2.8.0-rc01"
compose-runtime = "1.7.0-rc01"
compose-ui = "1.7.0-rc01"
coroutines = "1.8.1"
expresso-core = "3.6.1"
ext-junit = "1.2.1"
hilt = "2.52"
hilt-compose = "1.2.0"
junit = "4.13.2"
kotlin = "2.0.10"
kotlin-serialization = "1.7.1"
ksp = "2.0.10-1.0.24"
lifecycle-viewmodel = "2.8.4"
logging-interceptor = "5.0.0-alpha.14"
material = "1.12.0"
preference = "1.2.1"
retrofit = "2.11.0"
room = "2.7.0-alpha07"

[libraries]
accompanist-swiperefresh = { group = "com.google.accompanist", name = "accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-uicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose-foundation" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose-material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "compose-material3-adaptive" }
compose-material3-adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "compose-material3-adaptive" }
compose-material3-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "compose-material3-adaptive" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-material" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose-runtime" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-ui" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
expresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "expresso-core" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "ext-junit" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-compose" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlin-serialization-converter = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor" }
preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

[bundles]
accompanist = ["accompanist-swiperefresh", "accompanist-uicontroller"]
compose = ["compose-activity", "compose-foundation", "compose-material", "compose-material-icons", "compose-material3", "compose-navigation", "compose-runtime", "compose-ui", "compose-ui-tooling"]
compose-material3-adaptive = ["compose-material3-adaptive", "compose-material3-adaptive-layout", "compose-material3-adaptive-navigation"]
hilt = ["hilt-android", "hilt-compose"]
retrofit = ["logging-interceptor", "kotlin-serialization-converter", "retrofit"]
room = ["room-runtime", "room-ktx"]

[plugins]
agp = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
